import type { RoutePreview } from './types'

/**
 * Static sample route for the homepage preview:
 * India → Raxaul–Birgunj border → Kathmandu → Pokhara.
 * Illustrative only — not generated by the route planner.
 */
export const SAMPLE_ROUTE: RoutePreview = {
  id: 'sample-india-kathmandu-pokhara',
  points: [
    { longitude: 84.85, latitude: 26.98, label: 'Raxaul (India)' },
    { longitude: 84.88, latitude: 27.0, label: 'Birgunj' },
    { longitude: 85.324, latitude: 27.7172, label: 'Kathmandu' },
    { longitude: 83.9856, latitude: 28.2096, label: 'Pokhara' },
  ],
}
